version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  sut:
    build: . #TODO make this more efficient so it's not building twice? But also needs to work for different tags
    command: /usr/local/bin/runTests.sh
    environment:
      - DJANGO_DEBUG_MODE=True
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
